### ISSUE TITLE
ember-cli-sass downgrade

### ISSUE THREAD

**Issue by maxwondercorn** [kaermorchen/ember-cli-loaders#2]
Installing ember-cli-loaders downgrades ember-cli-sass to 6.2.0 which is a bit confusing.  The addon dependencies require  version 7.0.0 but the addon blueprint targets 6.1.1 .  

Not sure why is npm installed 6.2.0 installed instead of a 6.1.x version but shouldn't the blueprint target ^7.0.0?

Tested using ember-cli-sass version 7.2.0 and all tests pass

**Comment by kaermorchen** [comment]
It was my fail. I have updated ember-cli-sass to 7.0.0

**Comment by kaermorchen** [comment]
You can install latest version of `ember-cli-loaders` and change `ember-cli-sass` to 7.2.0 if do you need it.

**Comment by maxwondercorn** [comment]
Thanks for the nice addon.  I made the change and have it installed.
