### ISSUE TITLE
Better defaults or examples for new users

### ISSUE THREAD

**Issue by buzzware** [kaermorchen/ember-cli-loaders#3]
I thought this component wasn't working, as nothing appeared when I installed it. After fooling around trying to debug it, I discovered it was simply rendering white on white. 
Most projects begin with a white background. I suggest you change the default $primary-color to anything else eg. black.
In the documentation, it mentions that the $primary-color can be customised, but doesn't adequately communicate that changing it is likely necessary in order to see anything.
I suggest providing a simple example setting the foreground and background colors that is guaranteed to make the animations visible.

**Comment by kaermorchen** [comment]
Hello.

This is a wrapper, I can't change default values. I think the demo is enough to see how it work.
